export type ArticleStatus = 'draft' | 'published' | 'scheduled';

export interface Article {
  id?: string;

  title: string;
  description: string;

  // HTML generated by rich text editor
  content: string;

  thumbnail: string;

  authorId: string;
  authorName: string;

  createdAt?: Date;
  updatedAt?: Date;

  publishedAt?: Date | null;
  scheduledAt?: Date | null;

  status: ArticleStatus;

  views: number;

  featured: boolean;
  editorsPick: boolean;
}
